package uit.tkorg.cspublicationtool.entities;
// Generated Dec 4, 2011 5:00:43 PM by Hibernate Tools 3.2.1.GA



/**
 * RankAuthorSubdomainId generated by hbm2java
 */
public class RankAuthorSubdomainId  implements java.io.Serializable {


     private int idAuthor;
     private int idSubdomain;

    public RankAuthorSubdomainId() {
    }

    public RankAuthorSubdomainId(int idAuthor, int idSubdomain) {
       this.idAuthor = idAuthor;
       this.idSubdomain = idSubdomain;
    }
   
    public int getIdAuthor() {
        return this.idAuthor;
    }
    
    public void setIdAuthor(int idAuthor) {
        this.idAuthor = idAuthor;
    }
    public int getIdSubdomain() {
        return this.idSubdomain;
    }
    
    public void setIdSubdomain(int idSubdomain) {
        this.idSubdomain = idSubdomain;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RankAuthorSubdomainId) ) return false;
		 RankAuthorSubdomainId castOther = ( RankAuthorSubdomainId ) other; 
         
		 return (this.getIdAuthor()==castOther.getIdAuthor())
 && (this.getIdSubdomain()==castOther.getIdSubdomain());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdAuthor();
         result = 37 * result + this.getIdSubdomain();
         return result;
   }   


}


