package uit.tkorg.cspublicationtool.entities;
// Generated Nov 28, 2011 11:53:12 PM by Hibernate Tools 3.2.1.GA



/**
 * ConferencePcmemberId generated by hbm2java
 */
public class ConferencePcmemberId  implements java.io.Serializable {


     private int idConference;
     private int idPcmember;

    public ConferencePcmemberId() {
    }

    public ConferencePcmemberId(int idConference, int idPcmember) {
       this.idConference = idConference;
       this.idPcmember = idPcmember;
    }
   
    public int getIdConference() {
        return this.idConference;
    }
    
    public void setIdConference(int idConference) {
        this.idConference = idConference;
    }
    public int getIdPcmember() {
        return this.idPcmember;
    }
    
    public void setIdPcmember(int idPcmember) {
        this.idPcmember = idPcmember;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConferencePcmemberId) ) return false;
		 ConferencePcmemberId castOther = ( ConferencePcmemberId ) other; 
         
		 return (this.getIdConference()==castOther.getIdConference())
 && (this.getIdPcmember()==castOther.getIdPcmember());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdConference();
         result = 37 * result + this.getIdPcmember();
         return result;
   }   


}


