package uit.tkorg.cspublicationtool.entities;
// Generated Nov 30, 2011 8:42:51 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Keyword generated by hbm2java
 */
public class Keyword  implements java.io.Serializable {


     private Integer idKeyword;
     private String keyword;
     private String stemmingVariations;
     private String url;
     private Set papers = new HashSet(0);

    public Keyword() {
    }

    public Keyword(String keyword, String stemmingVariations, String url, Set papers) {
       this.keyword = keyword;
       this.stemmingVariations = stemmingVariations;
       this.url = url;
       this.papers = papers;
    }
   
    public Integer getIdKeyword() {
        return this.idKeyword;
    }
    
    public void setIdKeyword(Integer idKeyword) {
        this.idKeyword = idKeyword;
    }
    public String getKeyword() {
        return this.keyword;
    }
    
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }
    public String getStemmingVariations() {
        return this.stemmingVariations;
    }
    
    public void setStemmingVariations(String stemmingVariations) {
        this.stemmingVariations = stemmingVariations;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getPapers() {
        return this.papers;
    }
    
    public void setPapers(Set papers) {
        this.papers = papers;
    }




}


