package uit.tkorg.cspublicationtool.entities;
// Generated Nov 5, 2011 11:29:49 PM by Hibernate Tools 3.2.1.GA



/**
 * PaperPaper generated by hbm2java
 */
public class PaperPaper  implements java.io.Serializable {


     private PaperPaperId id;
     private Paper paperByIdPaperRef;
     private Paper paperByIdPaper;
     private String citationContext;

    public PaperPaper() {
    }

	
    public PaperPaper(PaperPaperId id, Paper paperByIdPaperRef, Paper paperByIdPaper) {
        this.id = id;
        this.paperByIdPaperRef = paperByIdPaperRef;
        this.paperByIdPaper = paperByIdPaper;
    }
    public PaperPaper(PaperPaperId id, Paper paperByIdPaperRef, Paper paperByIdPaper, String citationContext) {
       this.id = id;
       this.paperByIdPaperRef = paperByIdPaperRef;
       this.paperByIdPaper = paperByIdPaper;
       this.citationContext = citationContext;
    }
   
    public PaperPaperId getId() {
        return this.id;
    }
    
    public void setId(PaperPaperId id) {
        this.id = id;
    }
    public Paper getPaperByIdPaperRef() {
        return this.paperByIdPaperRef;
    }
    
    public void setPaperByIdPaperRef(Paper paperByIdPaperRef) {
        this.paperByIdPaperRef = paperByIdPaperRef;
    }
    public Paper getPaperByIdPaper() {
        return this.paperByIdPaper;
    }
    
    public void setPaperByIdPaper(Paper paperByIdPaper) {
        this.paperByIdPaper = paperByIdPaper;
    }
    public String getCitationContext() {
        return this.citationContext;
    }
    
    public void setCitationContext(String citationContext) {
        this.citationContext = citationContext;
    }




}


