package uit.tkorg.cspublicationtool.entities;
// Generated Nov 30, 2011 8:42:51 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Publisher generated by hbm2java
 */
public class Publisher  implements java.io.Serializable {


     private Integer idPublisher;
     private String namePublisher;
     private Set papers = new HashSet(0);

    public Publisher() {
    }

    public Publisher(String namePublisher, Set papers) {
       this.namePublisher = namePublisher;
       this.papers = papers;
    }
   
    public Integer getIdPublisher() {
        return this.idPublisher;
    }
    
    public void setIdPublisher(Integer idPublisher) {
        this.idPublisher = idPublisher;
    }
    public String getNamePublisher() {
        return this.namePublisher;
    }
    
    public void setNamePublisher(String namePublisher) {
        this.namePublisher = namePublisher;
    }
    public Set getPapers() {
        return this.papers;
    }
    
    public void setPapers(Set papers) {
        this.papers = papers;
    }




}


