package uit.tkorg.cspublicationtool.entities;
// Generated Nov 28, 2011 11:53:12 PM by Hibernate Tools 3.2.1.GA



/**
 * RankConferenceKeyword generated by hbm2java
 */
public class RankConferenceKeyword  implements java.io.Serializable {


     private RankConferenceKeywordId id;
     private Integer publicationCount;
     private Integer citationCount;
     private int rank;

    public RankConferenceKeyword() {
    }

	
    public RankConferenceKeyword(RankConferenceKeywordId id, int rank) {
        this.id = id;
        this.rank = rank;
    }
    public RankConferenceKeyword(RankConferenceKeywordId id, Integer publicationCount, Integer citationCount, int rank) {
       this.id = id;
       this.publicationCount = publicationCount;
       this.citationCount = citationCount;
       this.rank = rank;
    }
   
    public RankConferenceKeywordId getId() {
        return this.id;
    }
    
    public void setId(RankConferenceKeywordId id) {
        this.id = id;
    }
    public Integer getPublicationCount() {
        return this.publicationCount;
    }
    
    public void setPublicationCount(Integer publicationCount) {
        this.publicationCount = publicationCount;
    }
    public Integer getCitationCount() {
        return this.citationCount;
    }
    
    public void setCitationCount(Integer citationCount) {
        this.citationCount = citationCount;
    }
    public int getRank() {
        return this.rank;
    }
    
    public void setRank(int rank) {
        this.rank = rank;
    }




}


