package uit.tkorg.cspublicationtool.entities;
// Generated Nov 30, 2011 8:42:51 AM by Hibernate Tools 3.2.1.GA



/**
 * RankOrgSubdomain generated by hbm2java
 */
public class RankOrgSubdomain  implements java.io.Serializable {


     private RankOrgSubdomainId id;
     private Integer publicationCount;
     private Integer citationCount;
     private int rank;
     private Integer authorCount;

    public RankOrgSubdomain() {
    }

	
    public RankOrgSubdomain(RankOrgSubdomainId id, int rank) {
        this.id = id;
        this.rank = rank;
    }
    public RankOrgSubdomain(RankOrgSubdomainId id, Integer publicationCount, Integer citationCount, int rank, Integer authorCount) {
       this.id = id;
       this.publicationCount = publicationCount;
       this.citationCount = citationCount;
       this.rank = rank;
       this.authorCount = authorCount;
    }
   
    public RankOrgSubdomainId getId() {
        return this.id;
    }
    
    public void setId(RankOrgSubdomainId id) {
        this.id = id;
    }
    public Integer getPublicationCount() {
        return this.publicationCount;
    }
    
    public void setPublicationCount(Integer publicationCount) {
        this.publicationCount = publicationCount;
    }
    public Integer getCitationCount() {
        return this.citationCount;
    }
    
    public void setCitationCount(Integer citationCount) {
        this.citationCount = citationCount;
    }
    public int getRank() {
        return this.rank;
    }
    
    public void setRank(int rank) {
        this.rank = rank;
    }
    public Integer getAuthorCount() {
        return this.authorCount;
    }
    
    public void setAuthorCount(Integer authorCount) {
        this.authorCount = authorCount;
    }




}


