package uit.tkorg.cspublicationtool.entities;
// Generated Nov 30, 2011 8:42:51 AM by Hibernate Tools 3.2.1.GA



/**
 * RankPaperKeyword generated by hbm2java
 */
public class RankPaperKeyword  implements java.io.Serializable {


     private RankPaperKeywordId id;
     private Integer citationCount;
     private int rank;

    public RankPaperKeyword() {
    }

	
    public RankPaperKeyword(RankPaperKeywordId id, int rank) {
        this.id = id;
        this.rank = rank;
    }
    public RankPaperKeyword(RankPaperKeywordId id, Integer citationCount, int rank) {
       this.id = id;
       this.citationCount = citationCount;
       this.rank = rank;
    }
   
    public RankPaperKeywordId getId() {
        return this.id;
    }
    
    public void setId(RankPaperKeywordId id) {
        this.id = id;
    }
    public Integer getCitationCount() {
        return this.citationCount;
    }
    
    public void setCitationCount(Integer citationCount) {
        this.citationCount = citationCount;
    }
    public int getRank() {
        return this.rank;
    }
    
    public void setRank(int rank) {
        this.rank = rank;
    }




}


