package uit.tkorg.cspublicationtool.entities;
// Generated Dec 4, 2011 10:51:22 AM by Hibernate Tools 3.2.1.GA



/**
 * RankAuthorKeywordId generated by hbm2java
 */
public class RankAuthorKeywordId  implements java.io.Serializable {


     private int idAuthor;
     private int idKeyword;

    public RankAuthorKeywordId() {
    }

    public RankAuthorKeywordId(int idAuthor, int idKeyword) {
       this.idAuthor = idAuthor;
       this.idKeyword = idKeyword;
    }
   
    public int getIdAuthor() {
        return this.idAuthor;
    }
    
    public void setIdAuthor(int idAuthor) {
        this.idAuthor = idAuthor;
    }
    public int getIdKeyword() {
        return this.idKeyword;
    }
    
    public void setIdKeyword(int idKeyword) {
        this.idKeyword = idKeyword;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RankAuthorKeywordId) ) return false;
		 RankAuthorKeywordId castOther = ( RankAuthorKeywordId ) other; 
         
		 return (this.getIdAuthor()==castOther.getIdAuthor())
 && (this.getIdKeyword()==castOther.getIdKeyword());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdAuthor();
         result = 37 * result + this.getIdKeyword();
         return result;
   }   


}


