package uit.tkorg.cspublicationtool.entities;
// Generated Nov 5, 2011 11:29:49 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Subdomain generated by hbm2java
 */
public class Subdomain  implements java.io.Serializable {


     private Integer idSubdomain;
     private Domain domain;
     private String subdomainName;
     private Set papers = new HashSet(0);

    public Subdomain() {
    }

	
    public Subdomain(Domain domain) {
        this.domain = domain;
    }
    public Subdomain(Domain domain, String subdomainName, Set papers) {
       this.domain = domain;
       this.subdomainName = subdomainName;
       this.papers = papers;
    }
   
    public Integer getIdSubdomain() {
        return this.idSubdomain;
    }
    
    public void setIdSubdomain(Integer idSubdomain) {
        this.idSubdomain = idSubdomain;
    }
    public Domain getDomain() {
        return this.domain;
    }
    
    public void setDomain(Domain domain) {
        this.domain = domain;
    }
    public String getSubdomainName() {
        return this.subdomainName;
    }
    
    public void setSubdomainName(String subdomainName) {
        this.subdomainName = subdomainName;
    }
    public Set getPapers() {
        return this.papers;
    }
    
    public void setPapers(Set papers) {
        this.papers = papers;
    }




}


