package uit.tkorg.cspublicationtool.entities;
// Generated Nov 30, 2011 8:42:51 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Author generated by hbm2java
 */
public class Author  implements java.io.Serializable {


     private Integer idAuthor;
     private Org org;
     private String authorName;
     private String image;
     private String emailAddress;
     private String website;
     private Integer HIndex;
     private Integer GIndex;
     private String url;
     private Set authorinstances = new HashSet(0);
     private Set papers = new HashSet(0);

    public Author() {
    }

    public Author(Org org, String authorName, String image, String emailAddress, String website, Integer HIndex, Integer GIndex, String url, Set authorinstances, Set papers) {
       this.org = org;
       this.authorName = authorName;
       this.image = image;
       this.emailAddress = emailAddress;
       this.website = website;
       this.HIndex = HIndex;
       this.GIndex = GIndex;
       this.url = url;
       this.authorinstances = authorinstances;
       this.papers = papers;
    }
   
    public Integer getIdAuthor() {
        return this.idAuthor;
    }
    
    public void setIdAuthor(Integer idAuthor) {
        this.idAuthor = idAuthor;
    }
    public Org getOrg() {
        return this.org;
    }
    
    public void setOrg(Org org) {
        this.org = org;
    }
    public String getAuthorName() {
        return this.authorName;
    }
    
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public Integer getHIndex() {
        return this.HIndex;
    }
    
    public void setHIndex(Integer HIndex) {
        this.HIndex = HIndex;
    }
    public Integer getGIndex() {
        return this.GIndex;
    }
    
    public void setGIndex(Integer GIndex) {
        this.GIndex = GIndex;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getAuthorinstances() {
        return this.authorinstances;
    }
    
    public void setAuthorinstances(Set authorinstances) {
        this.authorinstances = authorinstances;
    }
    public Set getPapers() {
        return this.papers;
    }
    
    public void setPapers(Set papers) {
        this.papers = papers;
    }




}


