package uit.tkorg.cspublicationtool.entities;
// Generated Nov 5, 2011 11:29:49 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Conference generated by hbm2java
 */
public class Conference  implements java.io.Serializable {


     private Integer idConference;
     private String conferenceName;
     private String website;
     private String organization;
     private String organizedLocation;
     private String duration;
     private Integer yearStart;
     private Integer yearEnd;
     private String url;
     private Set conferencePcmembers = new HashSet(0);
     private Set papers = new HashSet(0);
     private Set publishers = new HashSet(0);

    public Conference() {
    }

    public Conference(String conferenceName, String website, String organization, String organizedLocation, String duration, Integer yearStart, Integer yearEnd, String url, Set conferencePcmembers, Set papers, Set publishers) {
       this.conferenceName = conferenceName;
       this.website = website;
       this.organization = organization;
       this.organizedLocation = organizedLocation;
       this.duration = duration;
       this.yearStart = yearStart;
       this.yearEnd = yearEnd;
       this.url = url;
       this.conferencePcmembers = conferencePcmembers;
       this.papers = papers;
       this.publishers = publishers;
    }
   
    public Integer getIdConference() {
        return this.idConference;
    }
    
    public void setIdConference(Integer idConference) {
        this.idConference = idConference;
    }
    public String getConferenceName() {
        return this.conferenceName;
    }
    
    public void setConferenceName(String conferenceName) {
        this.conferenceName = conferenceName;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public String getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(String organization) {
        this.organization = organization;
    }
    public String getOrganizedLocation() {
        return this.organizedLocation;
    }
    
    public void setOrganizedLocation(String organizedLocation) {
        this.organizedLocation = organizedLocation;
    }
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }
    public Integer getYearStart() {
        return this.yearStart;
    }
    
    public void setYearStart(Integer yearStart) {
        this.yearStart = yearStart;
    }
    public Integer getYearEnd() {
        return this.yearEnd;
    }
    
    public void setYearEnd(Integer yearEnd) {
        this.yearEnd = yearEnd;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getConferencePcmembers() {
        return this.conferencePcmembers;
    }
    
    public void setConferencePcmembers(Set conferencePcmembers) {
        this.conferencePcmembers = conferencePcmembers;
    }
    public Set getPapers() {
        return this.papers;
    }
    
    public void setPapers(Set papers) {
        this.papers = papers;
    }
    public Set getPublishers() {
        return this.publishers;
    }
    
    public void setPublishers(Set publishers) {
        this.publishers = publishers;
    }




}


