package uit.tkorg.cspublicationtool.entities;
// Generated Nov 5, 2011 11:29:49 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Journal generated by hbm2java
 */
public class Journal  implements java.io.Serializable {


     private Integer idJournal;
     private String journalName;
     private String website;
     private Integer yearStart;
     private Integer yearEnd;
     private String organization;
     private String url;
     private Set papers = new HashSet(0);

    public Journal() {
    }

    public Journal(String journalName, String website, Integer yearStart, Integer yearEnd, String organization, String url, Set papers) {
       this.journalName = journalName;
       this.website = website;
       this.yearStart = yearStart;
       this.yearEnd = yearEnd;
       this.organization = organization;
       this.url = url;
       this.papers = papers;
    }
   
    public Integer getIdJournal() {
        return this.idJournal;
    }
    
    public void setIdJournal(Integer idJournal) {
        this.idJournal = idJournal;
    }
    public String getJournalName() {
        return this.journalName;
    }
    
    public void setJournalName(String journalName) {
        this.journalName = journalName;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public Integer getYearStart() {
        return this.yearStart;
    }
    
    public void setYearStart(Integer yearStart) {
        this.yearStart = yearStart;
    }
    public Integer getYearEnd() {
        return this.yearEnd;
    }
    
    public void setYearEnd(Integer yearEnd) {
        this.yearEnd = yearEnd;
    }
    public String getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(String organization) {
        this.organization = organization;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getPapers() {
        return this.papers;
    }
    
    public void setPapers(Set papers) {
        this.papers = papers;
    }




}


