package uit.tkorg.cspublicationtool.entities;
// Generated Nov 28, 2011 11:53:12 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Magazine generated by hbm2java
 */
public class Magazine  implements java.io.Serializable {


     private Integer idMagazine;
     private String magazineName;
     private String website;
     private Integer yearStart;
     private Integer yearEnd;
     private String organization;
     private String url;
     private Set papers = new HashSet(0);

    public Magazine() {
    }

    public Magazine(String magazineName, String website, Integer yearStart, Integer yearEnd, String organization, String url, Set papers) {
       this.magazineName = magazineName;
       this.website = website;
       this.yearStart = yearStart;
       this.yearEnd = yearEnd;
       this.organization = organization;
       this.url = url;
       this.papers = papers;
    }
   
    public Integer getIdMagazine() {
        return this.idMagazine;
    }
    
    public void setIdMagazine(Integer idMagazine) {
        this.idMagazine = idMagazine;
    }
    public String getMagazineName() {
        return this.magazineName;
    }
    
    public void setMagazineName(String magazineName) {
        this.magazineName = magazineName;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public Integer getYearStart() {
        return this.yearStart;
    }
    
    public void setYearStart(Integer yearStart) {
        this.yearStart = yearStart;
    }
    public Integer getYearEnd() {
        return this.yearEnd;
    }
    
    public void setYearEnd(Integer yearEnd) {
        this.yearEnd = yearEnd;
    }
    public String getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(String organization) {
        this.organization = organization;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getPapers() {
        return this.papers;
    }
    
    public void setPapers(Set papers) {
        this.papers = papers;
    }




}


