package uit.tkorg.cspublicationtool.entities;
// Generated Nov 28, 2011 11:53:12 PM by Hibernate Tools 3.2.1.GA



/**
 * PaperReviewerId generated by hbm2java
 */
public class PaperReviewerId  implements java.io.Serializable {


     private int idPaper;
     private int idReviewer;

    public PaperReviewerId() {
    }

    public PaperReviewerId(int idPaper, int idReviewer) {
       this.idPaper = idPaper;
       this.idReviewer = idReviewer;
    }
   
    public int getIdPaper() {
        return this.idPaper;
    }
    
    public void setIdPaper(int idPaper) {
        this.idPaper = idPaper;
    }
    public int getIdReviewer() {
        return this.idReviewer;
    }
    
    public void setIdReviewer(int idReviewer) {
        this.idReviewer = idReviewer;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PaperReviewerId) ) return false;
		 PaperReviewerId castOther = ( PaperReviewerId ) other; 
         
		 return (this.getIdPaper()==castOther.getIdPaper())
 && (this.getIdReviewer()==castOther.getIdReviewer());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPaper();
         result = 37 * result + this.getIdReviewer();
         return result;
   }   


}


