package uit.tkorg.cspublicationtool.entities;
// Generated Dec 4, 2011 10:51:22 AM by Hibernate Tools 3.2.1.GA



/**
 * PaperPaperId generated by hbm2java
 */
public class PaperPaperId  implements java.io.Serializable {


     private int idPaper;
     private int idPaperRef;

    public PaperPaperId() {
    }

    public PaperPaperId(int idPaper, int idPaperRef) {
       this.idPaper = idPaper;
       this.idPaperRef = idPaperRef;
    }
   
    public int getIdPaper() {
        return this.idPaper;
    }
    
    public void setIdPaper(int idPaper) {
        this.idPaper = idPaper;
    }
    public int getIdPaperRef() {
        return this.idPaperRef;
    }
    
    public void setIdPaperRef(int idPaperRef) {
        this.idPaperRef = idPaperRef;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PaperPaperId) ) return false;
		 PaperPaperId castOther = ( PaperPaperId ) other; 
         
		 return (this.getIdPaper()==castOther.getIdPaper())
 && (this.getIdPaperRef()==castOther.getIdPaperRef());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPaper();
         result = 37 * result + this.getIdPaperRef();
         return result;
   }   


}


