package uit.tkorg.cspublicationtool.entities;
// Generated Nov 5, 2011 11:29:49 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Publisher generated by hbm2java
 */
public class Publisher  implements java.io.Serializable {


     private Integer idPublisher;
     private String namePublisher;
     private Set conferences = new HashSet(0);
     private Set papers = new HashSet(0);

    public Publisher() {
    }

    public Publisher(String namePublisher, Set conferences, Set papers) {
       this.namePublisher = namePublisher;
       this.conferences = conferences;
       this.papers = papers;
    }
   
    public Integer getIdPublisher() {
        return this.idPublisher;
    }
    
    public void setIdPublisher(Integer idPublisher) {
        this.idPublisher = idPublisher;
    }
    public String getNamePublisher() {
        return this.namePublisher;
    }
    
    public void setNamePublisher(String namePublisher) {
        this.namePublisher = namePublisher;
    }
    public Set getConferences() {
        return this.conferences;
    }
    
    public void setConferences(Set conferences) {
        this.conferences = conferences;
    }
    public Set getPapers() {
        return this.papers;
    }
    
    public void setPapers(Set papers) {
        this.papers = papers;
    }




}


