package uit.tkorg.cspublicationtool.entities;
// Generated Nov 30, 2011 8:42:51 AM by Hibernate Tools 3.2.1.GA



/**
 * RankOrgSubdomainId generated by hbm2java
 */
public class RankOrgSubdomainId  implements java.io.Serializable {


     private int idOrg;
     private int idSubdomain;

    public RankOrgSubdomainId() {
    }

    public RankOrgSubdomainId(int idOrg, int idSubdomain) {
       this.idOrg = idOrg;
       this.idSubdomain = idSubdomain;
    }
   
    public int getIdOrg() {
        return this.idOrg;
    }
    
    public void setIdOrg(int idOrg) {
        this.idOrg = idOrg;
    }
    public int getIdSubdomain() {
        return this.idSubdomain;
    }
    
    public void setIdSubdomain(int idSubdomain) {
        this.idSubdomain = idSubdomain;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RankOrgSubdomainId) ) return false;
		 RankOrgSubdomainId castOther = ( RankOrgSubdomainId ) other; 
         
		 return (this.getIdOrg()==castOther.getIdOrg())
 && (this.getIdSubdomain()==castOther.getIdSubdomain());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdOrg();
         result = 37 * result + this.getIdSubdomain();
         return result;
   }   


}


